### ISSUE TITLE
Въпроси относно условията за домашно

### ISSUE THREAD

**Issue by NoHomey** [heitara/swift-3#13]
Какъв точно е вида на изразите в Задача 2? Даден е пример без да е даден самия вид?

Това значи ли че вида на изразите е `(a opt1 b ) opt2 c` , където `a, b и c` са конкретни цели числа, а `opt1, opt2` са една от изброените операции?

Каква е идеята на задача 4? Да създава bounded expressions? Тоест да парсва изрази от вида:

 `(a opt1 b  opt2 c) opt3 d ` и да създава "шаблонен израз", на който да пресмята стойността при подаване на конкретни целочислени стойности на операндите?

**Comment by heitara** [comment]
Относно задача 2 - изразът е с произволно ниво на влагане на под-изрази, като няма променливи, а има само числа, скоби между всички операции (скобите може и да не са садължителни, ако се въведе приоритет).

Задача 4 - изразите можем да опишем със следната.

операция := ^
операция := *
операция := /
операция := +
операция := -

израз := число 
израз := променлива
израз := (израз операция израз)

За да изчислим стойността, трябва да предоставим заместване на променливите с конкретни стойности (реални числа).
